project:
  type: website

website:
  title: "annlian-site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer: "© 2025 Ann Lian"

editor: visual
output-dir: docs


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

